language: ruby

sudo: false

cache: bundler

services: mongodb

rvm:
  - 2.5
  - ruby-head
  - jruby-9.1.15.0

before_install:
  - gem update --system
  - gem update bundler

before_script:
  - bundle exec danger

addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
